### ISSUE TITLE
Mailchimp_ValidationError: Validation error: "Invalid Form Fields"

### ISSUE THREAD

**Issue by CecileBr** [WordPressUtilities/wpunewsletter#2]
Hi,

I am using the widget with Mailchimp and it returns an error. Could it be because the Mailchimp vendor is still using the 2.0 API ? It's deprecated since 12-31-2016 and, even though this one is not yet, Mailchimp is shuting down routes one by one.
Do you plan to switch to the 3.0 version ?

``` log
[06-Nov-2023 11:27:36 UTC] PHP Fatal error:  Uncaught Mailchimp_ValidationError: Validation error: "Invalid Form Fields" in /app/public/wp-content/plugins/wpunewsletter/inc/mailchimp/Mailchimp.php:253
Stack trace:
#0 /app/public/wp-content/plugins/wpunewsletter/inc/mailchimp/Mailchimp.php(228): Mailchimp->castError(Array)
#1 /app/public/wp-content/plugins/wpunewsletter/inc/mailchimp/Mailchimp/Lists.php(744): Mailchimp->call('lists/subscribe', '{"id":"72497f13...')
#2 /app/public/wp-content/plugins/wpunewsletter/wpunewsletter.php(798): Mailchimp_Lists->subscribe('72497f13f8', Array, NULL, 'html', true, true)
#3 /app/public/wp-includes/class-wp-hook.php(307): WPUNewsletter->mailchimp_register(Array, Array)
#4 /app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', A in /app/public/wp-content/plugins/wpunewsletter/inc/mailchimp/Mailchimp.php on line 253
```

Thanks!

**Comment by Darklg** [comment]
Hi @CecileBr sorry for the delay, i will look at this

**Comment by Darklg** [comment]
@CecileBr again, sorry for the delay, i've updated the plugin for the new Mailchimp API. Thanks for the reminder.

**Comment by CecileBr** [comment]
Thank you!
